config/routes.rb
Rails.application.routes.draw do

	root 'realestates#index'
	
  resources :realestates
  delete '/realestates/:realestate_id/pictures/:id', to: 'pictures#destroy', as: :destroy_realestate_picture
	devise_for :users, controllers: { registrations: "registrations"}

	get '/admin', to: 'realestates#admin', as: :admin

	get '/companies', to: 'company#index', as: :companies
	post '/companies', to: 'company#create'
	get '/company/new', to: 'company#new', as: :new_company
	get '/company/:id/edit', to: 'company#edit', as: :edit_company
	get 'company/:id', to: 'company#show', as: :company
	patch '/company/:id', to: 'company#update', as: :patch_company
	put '/company/:id', to: 'company#update', as: :put_company

	get '/contact', to: 'messages#new', as: :contact
	post 'contact', to: 'messages#create'

	post '/realestates/:id', to: 'realestates#send_message'
end

app/models/realestate.rb
class Realestate < ApplicationRecord
	extend Enumerize

	has_many :pictures, :dependent => :destroy
	
	enumerize :re_type, in: [:house, :apartment, :rural, :plot, :shed]
	enumerize :category, in: [:rent, :sale, :both]

  validates :re_type, :street, :district, :city, :state, :category, :price, presence: true
  validates :price, numericality: { greater_than: 0 }

  # ensures the realestate has images
  scope :with_images, -> {left_outer_joins(:pictures).where('pictures.realestate_id IS NOT NULL').distinct}

	def self.search(search)
	  where("street LIKE ?", "%#{search}%")
	  	.or(where("district LIKE ?", "%#{search}%"))
	  	.or(where("city LIKE ?", "%#{search}%"))
	  	.or(where("state LIKE ?", "%#{search}%"))
	end

	def address
		"#{street}, #{district}, #{city} - #{state}"
	end
end

app/controllers/realestates_controller.rb
class RealestatesController < ApplicationController
  before_action :set_realestate, only: [:show, :edit, :update, :destroy, :send_message]

  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :admin]

  # GET /realestates
  # GET /realestates.json
  def index
    if params[:category]
      @realestates = Realestate.where(category: params[:category]).paginate(:page => params[:page], :per_page => 9)
    elsif params[:type]
      @realestates = Realestate.where(re_type: params[:type]).paginate(:page => params[:page], :per_page => 9)
    else
      @realestates = Realestate.all.paginate(:page => params[:page], :per_page => 9)
      # if realestate doesn't have image, the html.erb code won't work
      # using .with_images will prevent this
      @carousel = Realestate.with_images.limit(3).order('id desc')
    end

    if params[:search]
      @realestates = Realestate.search(params[:search]).order("created_at DESC").paginate(:page => params[:page], :per_page => 9)
    end
  end

  # GET /realestates/1
  # GET /realestates/1.json
  def show
    @message = Message.new
  end

  # GET /realestates/new
  def new
    @realestate = Realestate.new
  end

  # GET /realestates/1/edit
  def edit
  end

  # POST /realestates
  # POST /realestates.json
  def create
    @realestate = Realestate.new(realestate_params)

    respond_to do |format|
      if @realestate.save
        picture_params.each { |image| @realestate.pictures.create(image: image) } if picture_params

        format.html { redirect_to @realestate, :flash => {:success => t('created_realestate') }}
        format.json { render :show, status: :created, location: @realestate }
      else
        format.html { render :new }
        format.json { render json: @realestate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /realestates/1
  # PATCH/PUT /realestates/1.json
  def update
    respond_to do |format|
      if @realestate.update(realestate_params)
        picture_params.each { |image| @realestate.pictures.create(image: image) } if picture_params

        format.html { redirect_to @realestate, :flash => {:success => t('updated_realestate')}}
        format.json { render :show, status: :ok, location: @realestate }
      else
        format.html { render :edit }
        format.json { render json: @realestate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /realestates/1
  # DELETE /realestates/1.json
  def destroy
    @realestate.destroy
    respond_to do |format|
      format.html { redirect_to realestates_url, :flash => {:success => t('removed_realestate')}}
      format.json { head :no_content }
    end
  end

  def admin
    @realestates = Realestate.all.paginate(:page => params[:page], :per_page => 9)
    @company = Company.all.present?
  end

  def send_message
    @message = Message.new(message_params)

    respond_to do |format|
      if verify_recaptcha && @message.valid?
        ContactMailer.new_message(@message).deliver
        format.html { redirect_to @realestate, :flash => {:success => t(:message_sent)}}
        format.json { render :show, status: :ok, location: @realestate }
      else
        format.html { render :show }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_realestate
      @realestate = Realestate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def realestate_params
      params.require(:realestate).permit(:re_type, :street, :district, :city, :state, :category, :price, :description, :cover)
    end

    def picture_params
      params.fetch(:images, {})
    end

    def message_params
      params.require(:message).permit(:name, :email, :phone, :content)
    end
end

app/helpers/realestates_helper.rb
module RealestatesHelper

	def realestate_price(realestate)

		label = '<strong>'

		if realestate.category == Realestate.category.rent
			label << 'Aluguel:</strong> '
		elsif realestate.category == Realestate.category.sale
			label << 'Preço de venda:</strong> '
		end

		label << number_to_currency(realestate.price).to_s
		label.html_safe
	end
end

app/views/realestates/_form.html.erb
<%= form_for realestate, html: { multipart: true } do |f| %>
  <% if realestate.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(realestate.errors.count, t('error')) %> <%=t :error_saving %>:</h2>

      <ul>
      <% realestate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @realestate.pictures.present? %>
    <%@realestate.pictures.each do |picture|%>
      <div class="picture-card">
        <%= f.radio_button :cover, picture.id %>
        <%= f.fields_for :pictures, picture do |image_fields| %>
          <%= f.label :cover, :value => picture.id do %>
            <%= image_tag picture.image.url(:thumb) %>
          <% end %>
        <% end %>
        <div class="picture-options">
          <%= link_to destroy_realestate_picture_path(@realestate, picture), method: :delete, data: { confirm: t('confirmation')} do %>
            <i class="fa fa-trash-o"></i>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>

<div class="form">
  <div class="field form-group">
    <%= f.label Realestate.human_attribute_name(:re_type) %>
    <%= f.select :re_type, Realestate.re_type.options, {}, class: 'custom-select form-control' %>
  </div>

  <div class="field form-group">
    <%= f.text_field :street, class: 'form-control', placeholder: Realestate.human_attribute_name(:street) %>
  </div>

  <div class="field form-group">
    <%= f.text_field :district, class: 'form-control', placeholder: Realestate.human_attribute_name(:district) %>
  </div>

  <div class="field form-group row">
    <div class="col-sm-6">
      <%= f.text_field :city, class: 'form-control div-form-city', placeholder: Realestate.human_attribute_name(:city) %>
    </div>
    <div class="col-sm-6">
      <%= f.text_field :state, class: 'form-control', placeholder: Realestate.human_attribute_name(:state) %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label Realestate.human_attribute_name(:category) %>
    <%= f.select :category, Realestate.category.options, {}, class: 'custom-select form-control' %>
  </div>

  <div class="field form-group">
    <%= f.text_field :price, class: 'form-control', placeholder: Realestate.human_attribute_name(:price) %>
  </div>

  <div class="field form-group row">
    <%= f.label Realestate.human_attribute_name(:rooms), class: 'col-2 col-form-label' %>
    <div class="col-2">
      <%= f.text_field :rooms, class: 'form-control', placeholder: Realestate.human_attribute_name(:rooms) %>
    </div>

    <%= f.label Realestate.human_attribute_name(:bathrooms), class: 'col-2 col-form-label' %>
    <div class="col-2">
      <%= f.text_field :bathrooms, class: 'form-control', placeholder: Realestate.human_attribute_name(:bathrooms) %>
    </div>

    <%= f.label Realestate.human_attribute_name(:ensuites), class: 'col-2 col-form-label' %>
    <div class="col-2">
      <%= f.text_field :ensuites, class: 'form-control', placeholder: Realestate.human_attribute_name(:ensuites) %>
    </div>
  </div>

  <div class="field form-group row">
    <%= f.label Realestate.human_attribute_name(:kitchens), class: 'col-2 col-form-label' %>
    <div class="col-2">
      <%= f.text_field :kitchens, class: 'form-control', placeholder: Realestate.human_attribute_name(:kitchens) %>
    </div>

    <%= f.label Realestate.human_attribute_name(:living_rooms), class: 'col-2 col-form-label' %>
    <div class="col-2">
      <%= f.text_field :living_rooms, class: 'form-control', placeholder: Realestate.human_attribute_name(:living_rooms) %>
    </div>

    <%= f.label Realestate.human_attribute_name(:toilets), class: 'col-2 col-form-label' %>
    <div class="col-2">
      <%= f.text_field :toilets, class: 'form-control', placeholder: Realestate.human_attribute_name(:toilets) %>
    </div>
  </div>

  <div class="field form-group row">
    <%= f.label Realestate.human_attribute_name(:parking_spaces), class: 'col-2' %>
    <div class="col-2">
      <%= f.text_field :parking_spaces, class: 'form-control', placeholder: Realestate.human_attribute_name(:parking_spaces) %>
    </div>

    <%= f.label Realestate.human_attribute_name(:dining_rooms), class: 'col-2' %>
    <div class="col-2">
      <%= f.text_field :dining_rooms, class: 'form-control', placeholder: Realestate.human_attribute_name(:dining_rooms) %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.text_area :description, class: 'form-control', placeholder: Realestate.human_attribute_name(:description) %>
  </div>

  <div class="field form-group">
    <%= f.label Realestate.human_attribute_name(:photo) + "(s)" %>
    <%= file_field_tag "images[]", accept: 'image/*', multiple: true, class: 'form-control' %>
  </div>

  <div class="actions form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
</div>
<% end %>

app/views/realestates/admin.html.erb
<h1 class="title"><%= t('admin_area') %></h1>

<% if user_signed_in? %>
  <%= link_to t('add_realestate'), new_realestate_path, class: "btn btn-primary btn-sm" %>
<% end %>
<% unless @company %>
  <%= link_to t('to_config') + " " + t('company'), new_company_path, class: "btn btn-warning btn-sm" %>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th><%= t('id') %></th>
      <th><%= Realestate.human_attribute_name(:cover) %></th>
      <th><%= t('address') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @realestates.each do |realestate| %>
      <tr>
        <td><%= realestate.id %></td>
        <td>
	        <%= link_to edit_realestate_path(realestate) do %>
		        <% if realestate.cover.present? %>
		          <%= image_tag realestate.pictures.find(realestate.cover).image.url(:thumb) %>
		        <% elsif realestate.pictures.present? %>
		          <%= image_tag realestate.pictures.first.image.url(:thumb) %>
		        <% else %>
		          <div class="not-found-image"><i class="fa fa-camera fa-2x"></i></div>
		        <% end %>
		      <% end %>
      	</td>
        <td><%= realestate.address %></td>
        <td><%= link_to t('edit'), edit_realestate_path(realestate) %></td>
        <td>
        	<%= link_to realestate, method: :delete, data: { confirm: t('confirmation') } do %>
        		<i class="fa fa-trash-o"></i>
        	<% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @realestates, renderer: 'BootstrapPaginationHelper::LinkRenderer' %>

app/views/realestates/edit.html.erb
<h1 class="title form-title"><%= t('editing_realestate') %></h1>

<div class="form-buttons">
	<%= link_to t('show'), @realestate, class: "btn btn-secondary" %>
	<%= link_to t('back'), :back, class: "btn btn-secondary" %>
</div>

<%= render 'form', realestate: @realestate %>

app/views/realestates/index.html.erb
<% if @carousel.present? %>
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li class="first-slide active" data-target="#myCarousel" data-slide-to="0"></li>
    <li class="second-slide" data-target="#myCarousel" data-slide-to="1"></li>
    <li class="third-slide" data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <% @carousel.each_with_index do |re, index| %>
        <div class="carousel-item <%= index == 0 ? 'active' : ''%>">
        <%= link_to (image_tag re.pictures.first.image.url), re %>
          <div class="container">
            <div class="carousel-caption d-none d-md-block text-left">
              <h1><%= "#{re.district}, #{re.city} - #{re.state}" %></h1>
              <p><%= "#{t(re.re_type, scope: [:enumerize, :realestate, :re_type])} - #{t(re.category, scope: [:enumerize, :realestate, :category] )}" %></p>
            </div>
          </div>
      </div>
    <% end %>
  </div>
  <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<% end %>

<h1 class="title"><%= realestates_title(params) %></h1>

<div class="row">
  <% @realestates.each do |realestate| %>
    <div class="col-md-4">
      <%= link_to realestate do %>
        <% if realestate.cover.present? %>
          <%= image_tag realestate.pictures.find(realestate.cover).image.url(:medium) %>
        <% elsif realestate.pictures.present? %>
          <%= image_tag realestate.pictures.first.image.url(:medium) %>
        <% else %>
          <div class="not-found-image"><i class="fa fa-camera fa-2x"></i></div>
        <% end %>
      <% end %>
      <div>
        <%= t(realestate.re_type, scope: [:enumerize, :realestate, :re_type]) %> - <%=t realestate.category, scope: [:enumerize, :realestate, :category] %>
        <br>
        <%= "#{realestate.district} - #{realestate.city}" %>
        <p><%= number_to_currency realestate.price %></p>
      </div>
    </div>
  <% end %>
</div>

<%= will_paginate @realestates, renderer: 'BootstrapPaginationHelper::LinkRenderer' %>

app/views/realestates/new.html.erb
<h1 class="title"><%=t ('new') %> <%=t ('realestate') %></h1>

<%= render 'form', realestate: @realestate %>

<%= link_to t('back'), realestates_path %>

app/views/realestates/show.html.erb
<% if @message.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <ul>
        <% @message.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

<h3 class="title"><%= "#{t(:realestate).capitalize} Ref: #{@realestate.id}" %></h3>

<p class="picture-show">
  <%= lightbox_helper(@realestate.pictures)%>
</p>


<div class="row justify-content-between">
  <div class="col-sm-4">
    <p>
      <%= realestate_price(@realestate) %>
    </p>
    <ul class="list-group">
      <li class="list-group-item justify-content-between">
        <%= Realestate.human_attribute_name(:re_type) %>
        <span class="badge badge-default badge-pill"><%=t @realestate.re_type, scope: [:enumerize, :realestate, :re_type] %></span>
      </li>
      <li class="list-group-item justify-content-between">
        <%= Realestate.human_attribute_name(:category) %>
        <span class="badge badge-default badge-pill"><%=t @realestate.category, scope: [:enumerize, :realestate, :category] %></span>
      </li>
      <li class="list-group-item justify-content-between">
        <%= Realestate.human_attribute_name(:rooms) %>
        <span class="badge badge-default badge-pill"><%= @realestate.rooms %></span>
      </li>
      <li class="list-group-item justify-content-between">
        <%= Realestate.human_attribute_name(:bathrooms) %>
        <span class="badge badge-default badge-pill"><%= @realestate.bathrooms %></span>
      </li>
      <li class="list-group-item justify-content-between">
        <%= Realestate.human_attribute_name(:ensuites) %>
        <span class="badge badge-default badge-pill"><%= @realestate.ensuites %></span>
      </li>
      <li class="list-group-item justify-content-between">
        <%= Realestate.human_attribute_name(:living_rooms) %>
        <span class="badge badge-default badge-pill"><%= @realestate.living_rooms %></span>
      </li>
      <li class="list-group-item justify-content-between">
        <%= Realestate.human_attribute_name(:parking_spaces) %>
        <span class="badge badge-default badge-pill"><%= @realestate.parking_spaces %></span>
      </li>
    </ul>
  </div>
  <div class="col-sm-6">

    <h4>Alguma dúvida?</h4>

    <%= form_for @message, url: @realestate do |message_form| %>
      <div class="row">
        <div class="col-md-6">
          <div class="field form-group">
            <%= message_form.text_field :name, placeholder: true, class: 'form-control', required: true %>
          </div>

          <div class="field form-group">
            <%= message_form.email_field :email, placeholder: true, class: 'form-control', required: true %>
          </div>

          <div class="field form-group">
            <%= message_form.phone_field :phone, placeholder: true, class: 'form-control', pattern: '(^\(\d{2}\)\s\d{4,5}(-|\s)\d{4,5}|^\d{2}\s\d{4,5}(-|\s)\d{4,5})' %>
          </div>

          <%= recaptcha_tags class: 'field form-group' %>
        </div>
        <div class="col-md-6">
          <div class="field form-group">
            <%= message_form.text_area :content, placeholder: true, class: 'form-control', rows: 7, required: true %>
          </div>

          <div class="field form-group">
            <%= message_form.submit t('send'), class: "btn btn-success" %>
          </div>
        </div>
      </div>
    <% end %>

  </div>
</div>

<% if @realestate.description.present? %>
  <div class="row">
    <div class="col-12 col-md-auto margin-top">
      <strong><%= Realestate.human_attribute_name(:description) %>:</strong>
      <pre><%= @realestate.description %></pre>
    </div>
  </div>
<% end %>

<h3 class="title">
  <strong><i class="fa fa-map-marker"></i></strong>
  <%= @realestate.street %>, <%= @realestate.district %>,
  <%= @realestate.city %> - <%= @realestate.state %>
</h3>

<script>
      function initMap() {
        var uluru = '<%= "#{@realestate.street}, #{@realestate.district}, #{@realestate.city}, #{@realestate.state}" %>'
        var map = new google.maps.Map(document.getElementById('map'), { zoom: 16 });
        var geocoder = new google.maps.Geocoder;
        geocoder.geocode({'address': uluru}, function(results, status) {
          if (status === 'OK') {
            map.setCenter(results[0].geometry.location);
            new google.maps.Marker({
              map: map,
              position: results[0].geometry.location
            });
          } else {
            window.alert('Geocode was not successful for the following reason: ' +
                status);
          }
        });
      }
</script>

<div style='width: 100%;'>
  <div id="map" style='width: 100%; height: 400px;'></div>
</div>

<div class="social-share-links">
  <h5><i class="fa fa-share-alt"></i> <%= t(:share) %></h5>
  <%= link_to "#", class: "hvr-float-shadow", :onclick => "MyWindow=window.open('https://www.facebook.com/sharer/sharer.php?u=#{request.url}','MyWindow', width=600, height=300); return false;" do %>
    <i class="fa fa-2x fa-facebook-square share-link"></i>
  <% end %>
  <%= link_to "#", class: "hvr-float-shadow", :onclick => "MyWindow=window.open('https://twitter.com/home?status=#{request.url}','MyWindow', width=600, height=300); return false;" do %>
    <i class="fa fa-2x fa-twitter-square share-link"></i>
  <% end %>
  <%= link_to "#", class: "hvr-float-shadow", :onclick => "MyWindow=window.open('https://plus.google.com/share?url=#{request.url}','MyWindow', width=600, height=300); return false;" do %>
    <i class="fa fa-2x fa-google-plus-square share-link"></i>
  <% end %>
</div>

<p>
  <strong><%= t('added') %>:</strong>
  <%= @realestate.created_at.strftime('%d/%m/%Y - %Hh%Mm') %>
</p>


<% if user_signed_in? %>
  <%= link_to t('edit'), edit_realestate_path(@realestate) %> | 
  <%= link_to t('remove'), @realestate, method: :delete, data: { confirm: t('confirmation') } %>
<% end %>

<% content_for :javascript do %>
  <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDlyvKxnErCee57UucS2NZQLhTmDuuoCN0&callback=initMap"></script>
<% end %>



<% content_for :javascript do %>
  <%= javascript_include_tag "lightbox" %>
<% end %>