config/routes.rb
Rails.application.routes.draw do

	root 'realestates#index'
	
  resources :realestates
  delete '/realestates/:realestate_id/pictures/:id', to: 'pictures#destroy', as: :destroy_realestate_picture
	devise_for :users, controllers: { registrations: "registrations"}

	get '/admin', to: 'realestates#admin', as: :admin

	get '/companies', to: 'company#index', as: :companies
	post '/companies', to: 'company#create'
	get '/company/new', to: 'company#new', as: :new_company
	get '/company/:id/edit', to: 'company#edit', as: :edit_company
	get 'company/:id', to: 'company#show', as: :company
	patch '/company/:id', to: 'company#update', as: :patch_company
	put '/company/:id', to: 'company#update', as: :put_company

	get '/contact', to: 'messages#new', as: :contact
	post 'contact', to: 'messages#create'

	post '/realestates/:id', to: 'realestates#send_message'
end

app/views/layouts/_footer.html.erb
<footer id="footer" class="footer">
  <div class="container container-fluid">
    <div class="row">

      <div class="footer-follow col-md-4">
        <h4><%= t('follow_us') %></h4>
        <ul>
          <% if @agency.present? %>
            <% if @agency.facebook.present? %>
              <li>
                <%= link_to @agency.facebook, target: "_blank" do %>
                  <i class="fa fa-facebook-official fa-3x" aria-hidden="true"></i>
                <% end %>
              </li>
            <% end %>
            <% if @agency.twitter.present? %>
              <li>
                <%= link_to @agency.twitter, target: "_blank" do %>
                  <i class="fa fa-twitter-square fa-3x" aria-hidden="true"></i>
                <% end %>
              </li>
            <% end %>
            <% if @agency.instagram.present? %>
              <li>
                <%= link_to @agency.instagram, target: "_blank" do %>
                  <i class="fa fa-instagram fa-3x" aria-hidden="true"></i>
                <% end %>
              </li>
            <% end %>
            <% if @agency.google_plus.present? %>
              <li>
                <%= link_to @agency.google_plus, target: "_blank" do %>
                  <i class="fa fa-google-plus-square fa-3x" aria-hidden="true"></i>
                <% end %>
              </li>
            <% end %>
          <% else %>
            <li><a href="http://www.facebook.com/guihatano" target="_blank"><i class="fa fa-facebook-official fa-3x" aria-hidden="true"></i></a></li>
            <li><a href="https://twitter.com/guihatano" target="_blank"><i class="fa fa-twitter-square fa-3x"></i></a></li>
            <li><a href="https://www.instagram.com/guihatano/" target="_blank"><i class="fa fa-instagram fa-3x"></i></a></li>
          <% end %>
        </ul>
      </div>
      
      <div class="footer-contact col-md-4">
        <h4><%= t('contact_us') %></h4>
        <% if @agency.present? %>
          <p><i class="fa fa-map-marker"></i> <%= @agency.street_and_number %></p>
          <p> <%= @agency.city_and_state %></p>
          <p><i class="fa fa-phone"></i> <%= @agency.phone %></p>
          <p><%= @agency.email %></p>
        <% end %>
      </div>

      <div class="footer-menu col-md-4">
        <ul>
          <li><%= link_to "Home", root_path %></li>

          <li><%= link_to t('contact'), contact_path %></li>
          <li>
            <%= link_to admin_path do %>
              <i class="fa fa-lock"></i> <%= t('restricted_area') %>
            <% end %>
          </li>
        </ul>
      </div>

    </div>
  </div>
  <div class="copyright">
    <p>Copyright 2017 guiHatano Co. All Rights Reserved</p>
  </div>
</footer>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to "Imobiliária", root_path, class: "navbar-brand" %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to t('home'), root_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= Realestate.human_attribute_name(:category) %></a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to t('rent', scope: ["enumerize.realestate.category"]), root_path({ :category => Realestate.category.rent }), class: "dropdown-item" %>
          <%= link_to t('sale', scope: ["enumerize.realestate.category"]), root_path({ :category => Realestate.category.sale }), class: "dropdown-item" %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <%= link_to Realestate.human_attribute_name(:re_type), "", class: "nav-link dropdown-toggle", id: "navbarTypeMenuLink", 'data-toggle' => "dropdown" , aria: {haspopup: true, expanded: false} %>
        <div class="dropdown-menu" aria-labelledby="navbarTypeMenuLink">
          <% Realestate.re_type.values.each do |type| %>
            <%= link_to t(type, scope: [:enumerize, :realestate, :re_type]), root_path({ :type => type }), class: "dropdown-item" %>
          <% end %>
        </div>
      </li>
      <li class="nav-item">
        <%= link_to t('contact'), contact_path, class: "nav-link" %>
      </li>
    </ul>
    <%= form_tag(realestates_path, :method => "get", id: "search-form", class: "form-inline my-2 my-lg-0") do %>
      <%= text_field_tag :search, params[:search], placeholder: t('search_placeholder'), class: "form-control mr-sm-2" %>
      <%= submit_tag t('search'), class: "btn btn-outline-success my-2 my-sm-0" %>
    <% end %>

    <ul class="navbar-nav mr-0">
      <li class="nav-item <%= user_signed_in? ? 'dropdown' : '' %>">
        <% if user_signed_in? %>
          <a class="nav-link dropdown-toggle" id="navbar-settings-menu" href="#" data-toggle="dropdown"><i class="fa fa-ellipsis-v"></i></a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbar-settings-menu">
            <%= link_to 'Configurações', edit_company_path(@agency), class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        <% else %>
          <%= link_to new_user_session_path, class: "nav-link" do %>
            <i class="fa fa-sign-in"></i>
          <% end %>
        <% end %>
      </li>
    </ul>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Imobiliaria</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= yield :head %>
  </head>
  <body>
    <% cache(["v1-menu"]) do %>
      <%= render 'layouts/menu' %>
    <% end %>

    <div class="container-fluid">
      <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %> alert-dismissible fade show" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= value %>
        </div>
      <% end %>

      <%= yield %>
    </div>

    <% cache(["v1-footer"]) do %>
      <%= render 'layouts/footer', :locals => { :agency => @agency } %>
    <% end %>
    <%= yield :javascript %>
  </body>
</html>